---
k3s_control_node: true

k3s_server:
  node-ip: "{{ ansible_host }}"
  tls-san:
    - "192.168.0.5"
  docker: false
  flannel-backend: "none"
  disable:
    - flannel
    - traefik
    - servicelb
    - metrics-server
  disable-network-policy: true
  disable-cloud-controller: true
  write-kubeconfig-mode: "644"
  cluster-cidr: "10.42.0.0/16"
  service-cidr: "10.43.0.0/16"
  kubelet-arg:
    - "feature-gates=MixedProtocolLBService=true"
  kube-controller-manager-arg:
    - "feature-gates=MixedProtocolLBService=true"
    - "bind-address=0.0.0.0"
  kube-proxy-arg:
    - "feature-gates=MixedProtocolLBService=true"
    - "metrics-bind-address=0.0.0.0"
  kube-scheduler-arg:
    - "feature-gates=MixedProtocolLBService=true"
    - "bind-address=0.0.0.0"
  etcd-expose-metrics: true
  kube-apiserver-arg:
    - "feature-gates=MixedProtocolLBService=true"
    - "anonymous-auth=true"
