---
all:
  children:
    kube:
      children:
        k3s-servers:
          192.168.5.1:
          192.168.5.2:
          192.168.5.3:
        k3s-agents:
          192.168.6.1:
          192.168.6.2:
          192.168.6.3:
          192.168.6.4:
          192.168.6.5:
    storage:
      192.168.7.1:
