---
all:
  children:
    kube:
      children:
        k3sservers:
          hosts:
            k3s-server-01:
              ansible_host: 192.168.5.1
            k3s-server-02:
              ansible_host: 192.168.5.2
            k3s-server-03:
              ansible_host: 192.168.5.3
        k3sagents:
          hosts:
            k3s-agent-01:
              ansible_host: 192.168.6.1
            k3s-agent-02:
              ansible_host: 192.168.6.2
            k3s-agent-03:
              ansible_host: 192.168.6.3
            k3s-agent-04:
              ansible_host: 192.168.6.4
            k3s-agent-05:
              ansible_host: 192.168.6.5
    storage:
      hosts:
        k3s-storage-01:
          ansible_host: 192.168.7.1
