---
k3s_release_Version: "v1.25.3+k3s1"
k3s_install_hard_links: true
k3s_become: true
k3s_debug: false
k3s_etcd_datastore: true
k3s_use_unsupported_config: true
k3s_registration_address: "192.168.0.5"
k3s_server_manifests_urls:
  - url: https://docs.projectcalico.org/archive/v3.24/manifests/tigera-operator.yaml
    filename: tigera-operator.yaml
  - url: https://kube-vip.io/manifests/rbac.yaml
    filename: kube-vip-rbac.yaml
# (list) A flat list of templates to deploy on the primary control plane
# /var/lib/rancher/k3s/server/manifests
k3s_server_manifests_templates:
  - "calico-installation.yaml.j2"
  - kube-vip-daemonset.yaml.j2
