---
- name: Install K3S
  hosts:
    - k3s-servers
    - k3s-agents
  become: true
  gather_facts: true
  any_errors_fatal: true
  strategy: linear
  pre_tasks:
    - name: Pausing for 5 seconds...
      ansible.builtin.pause:
        seconds: 5
  tasks:
    - name: Check if cluster is installed
      check_mode: false
      ansible.builtin.stat:
        path: "/etc/rancher/k3s/config.yaml"
      register: k3s_check_installed
    - name: Set manifest facts
      ansible.builtin.set_fact:
        k3s_server_manifests_templates: []
        k3s_server_manifests_urls: []
      when: k3s_check_installed.stat.exists
    - name: Install K3S
      ansible.builtin.include_role:
        name: xanmanning.k3s
        public: true
      vars:
        k3s_state: installed
    - name: Copy kubeconfig to local machine
      run_once: true # noqa run-once
      ansible.builtin.fetch:
        src: "/etc/rancher/k3s/k3s.yaml"
        dest: "{{ base }}/kubeconfig"
        flat: true
      when:
        - k3s_control_node is defined
        - k3s_control_node
    - name: Update kubeconfig with the correct IPv4 address
      delegate_to: localhost
      become: false
      run_once: true # noqa run-once
      ansible.builtin.replace:
        path: "{{ base }}/kubeconfig"
        regexp: "https://127.0.0.1:6443"
        replace: "https://{{ k3s_registration_addresss }}:6443"
    - name: Wait for k3s to finish installing the deployed manifests
      ansible.builtin.wait_for:
        timeout: 15
      when: k3s_server_manifests_templates | length > 0
        or k3s_server_manifests_dir | length > 0
    - name: Remove deployed manifest templates
      ansible.builtin.file:
        path: "{{ k3s_server_manifests_dir }}/{{ item | basename | regex_replace('\\.j2$', '') }}"
        state: absent
      loop: "{{ k3s_server_manifests_templates | default([]) }}"

    - name: Remove deployed manifest urls
      ansible.builtin.file:
        path: "{{ k3s_server_manifests_dir }}/{{ item.filename }}"
        state: absent
      loop: "{{ k3s_server_manifests_urls | default([]) }}"
